### PR TITLE
correct spelling error from hot to how

### PR DESCRIPTION
**Pull request by nickyrabit**
There is a spelling error in the document.

### CODE REVIEW

**Comment by fend25** [comment]
Hi @nickyrabit !

Appreciate so much your attention and thank you for the fix!

Could you please remove the yarn.lock changes from the PR as it is not related to the PR subject. Thank you.

**Comment by fend25** [comment]
Hi again, @nickyrabit !

Unfortunately, you've deleted the whole yarn.lock file while we just don't need any changed in the yarn.lock. Could you please remove the yarn.loch *changes*, not the yarn.lock at all?

**Comment by nickyrabit** [comment]
i have returned the yarn.lock as it was

**Comment by fend25** [comment]
Thank you!
Merged.

**Pull request merged**
